### ISSUE TITLE
submodules incompatible with downgraded torch by torch-scatter

### ISSUE THREAD

**Issue by nicholasnge** [KeKsBoTer/c3dgs#4]
Hello, looking forward to run your code. 
However, when I run the conda env setup, I get the error below during pip install submodules. 
Alternatively, when I manually install the packages, i can pip install submodules but thereafter torch-scatter is incompatible since it downgrades torch to 1.12 from 2.2.2

Wondering how you managed to set it up? Thanks!

```
Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      running bdist_wheel
      running build
      running build_py
      copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-38\diff_gaussian_rasterization
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Nicholas\Desktop\3DGS 5342\c3dgs\submodules\diff-gaussian-rasterization\setup.py", line 18, in <>
          setup(
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\_distutils\core.py", line 185, ip
          return run_commands(dist)
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\_distutils\core.py", line 201, is
          dist.run_commands()
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\_distutils\dist.py", line 969, is
          self.run_command(cmd)
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\dist.py", line 967, in run_commad
          super().run_command(command)
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\_distutils\dist.py", line 988, id
          cmd_obj.run()
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\_distutils\cmd.py", line 318, ind
          self.distribution.run_command(command)
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\dist.py", line 967, in run_commad
          super().run_command(command)
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\_distutils\dist.py", line 988, id
          cmd_obj.run()
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\_distutils\command\build.py", lin
          self.run_command(cmd_name)
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\_distutils\cmd.py", line 318, ind
          self.distribution.run_command(command)
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\dist.py", line 967, in run_commad
          super().run_command(command)
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\_distutils\dist.py", line 988, id
          cmd_obj.run()
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\command\build_ext.py", line 91, n
          _build_ext.run(self)
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\setuptools\_distutils\command\build_ext.py"n
          self.build_extensions()
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\torch\utils\cpp_extension.py", line 434, ins
          self._check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\Nicholas\.conda\envs\c3dgs-envfile\lib\site-packages\torch\utils\cpp_extension.py", line 812, inn
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.1) mismatches the version that was used to compile
      PyTorch (11.6). Please make sure to use the same CUDA versions.

```

**Comment by nicholasnge** [comment]
looks like the conda install didnt quite work for me, 
but the pip install works, solved
